@startuml
  start
  repeat
    partition Wczytywanie {
      :Wczytaj ścieżkę pliku wejściowego;
      #LightBlue:Wyświetl oryginalny sygnał;
    }
    #LightGray:Powtórz := tak;
    repeat
      partition Filtracja {
        :Wczytaj parametry algorytmu;
        :Przeprowadź filtrację sygnału;
        #LightBlue:Wyświetl zmodyfikowany sygnał;
      }
      :Akcja użytkownika;
        if (Zapisz?) then (tak)
          partition Zapis {
            :Wczytaj ścieżkę pliku wyjściowego;
            :Zapisz plik;
          }
        elseif (Anuluj?) then (tak)
          #LightGray:Powtórz := nie;
        elseif (Zakończ?) then (tak)
          end
        else (Powtórz)
        endif;
    repeat while (Powtórz?) is (tak)
@enduml
